sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- make --directory=monografia && mv monografia/main.pdf pagina/monografia.pdf
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: pagina/
  on:
    branch: gh-pages